# Generated by Django 5.2 on 2026-04-14 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appointment_google_event_id_appointment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonio',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
