# Generated by Django 5.2 on 2026-05-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testimonio_rating_testimonio_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='cellphone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
