# Generated by Django 5.2 on 2026-07-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_patient_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonio',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
